### ISSUE TITLE
Install of ghetto-vcb vib or offline bundle failes with error [ValueError]  Expected 1 component, found 2

### ISSUE THREAD

**Issue by Cardy165** [lamw/ghettoVCB#253]
I'm trying to install the vghetto-vcb big onto the nodes of an ESX cluster. 

The cluster nodes are running: VMware ESXi, 7.0.3, 18825058

I have tried to use both the vib and the offline bundle but both fail with a python error according to the logs

```
esxcli software vib install -
v file:///vmfs/volumes/backup-1/ghettoVCB-vib/vghetto-ghettoVCB.vib -f
 [ValueError]
 Expected 1 component, found 2
 Please refer to the log file for more details.
```

Checking the esxupdate log shows the following error:

```
2021-11-03T11:19:37Z esxupdate: 2119218: root: INFO: Command = vib.install
2021-11-03T11:19:37Z esxupdate: 2119218: root: INFO: Options = {'depot': None, 'viburl': ['file:///vmfs/volumes/backup-1/ghettoVCB-vib/vghetto-ghettoVCB.vib'], 'nameid': None, 'profile': None, 'baseimageversion': None, 'addon': None, 'softwarespec': None, 'level': None, 'updateonly': False, 'noliveinstall': False, 'nomaintmode': False, 'force': True, 'dryrun': False, 'oktoremove': False, 'proxy': None, 'nosigcheck': False, 'pending': None, 'rebooting': False, 'downgrade': None, 'nohwwarning': False}
2021-11-03T11:19:39Z esxupdate: 2119218: HostImage: INFO: Installers initiated are {'live': <vmware.esximage.Installer.LiveImageInstaller.LiveImageInstaller object at 0x287d4fe3a0>, 'boot': <vmware.esximage.Installer.BootBankInstaller.BootBankInstaller object at 0x287d7eb790>, 'locker': <vmware.esximage.Installer.LockerInstaller.LockerInstaller object at 0x287d7eb1c0>}
2021-11-03T11:19:39Z esxupdate: 2119218: imageprofile: INFO: Adding VIB VMware_locker_tools-light_11.3.5.18557794-18558696 to ImageProfile (Updated) DEL-ESXi-702_17867351-A04
2021-11-03T11:19:39Z esxupdate: 2119218: imageprofile: DEBUG: Adding Component TOOLS-18558696 to ImageProfile (Updated) DEL-ESXi-702_17867351-A04
2021-11-03T11:19:39Z esxupdate: 2119218: HostImage: DEBUG: Deferring initiating installers
2021-11-03T11:19:40Z esxupdate: 2119218: HostImage: INFO: Installers initiated are {'live': <vmware.esximage.Installer.LiveImageInstaller.LiveImageInstaller object at 0x287d6749a0>, 'boot': <vmware.esximage.Installer.BootBankInstaller.BootBankInstaller object at 0x287de8aaf0>, 'locker': <vmware.esximage.Installer.LockerInstaller.LockerInstaller object at 0x287d722be0>}
2021-11-03T11:19:40Z esxupdate: 2119218: imageprofile: INFO: Adding VIB VMware_locker_tools-light_11.3.5.18557794-18558696 to ImageProfile (Updated) DEL-ESXi-702_17867351-A04
2021-11-03T11:19:40Z esxupdate: 2119218: imageprofile: DEBUG: Adding Component TOOLS-18558696 to ImageProfile (Updated) DEL-ESXi-702_17867351-A04
2021-11-03T11:19:40Z esxupdate: 2119218: Transaction: DEBUG: Metadata is provided, skip download
2021-11-03T11:19:40Z esxupdate: 2119218: Transaction: INFO: Skipping installed VIBs
2021-11-03T11:19:40Z esxupdate: 2119218: Transaction: INFO: Final list of VIBs being installed: virtuallyGhetto_bootbank_ghettoVCB_1.0.0-0.0.0
2021-11-03T11:19:40Z esxupdate: 2119218: imageprofile: INFO: Adding VIB virtuallyGhetto_bootbank_ghettoVCB_1.0.0-0.0.0 to ImageProfile (Updated) DEL-ESXi-702_17867351-A04
2021-11-03T11:19:40Z esxupdate: 2119218: root: ERROR: Traceback (most recent call last):
2021-11-03T11:19:40Z esxupdate: 2119218: root: ERROR:   File "/usr/lib/vmware/esxcli-software", line 773, in <module>
2021-11-03T11:19:40Z esxupdate: 2119218: root: ERROR:     main()
2021-11-03T11:19:40Z esxupdate: 2119218: root: ERROR:   File "/usr/lib/vmware/esxcli-software", line 764, in main
2021-11-03T11:19:40Z esxupdate: 2119218: root: ERROR:     ret = CMDTABLE[command](options)
2021-11-03T11:19:40Z esxupdate: 2119218: root: ERROR:   File "/usr/lib/vmware/esxcli-software", line 601, in VibInstallCmd
2021-11-03T11:19:40Z esxupdate: 2119218: root: ERROR:     res = t.InstallVibsFromSources(viburls, [], nameids,
2021-11-03T11:19:40Z esxupdate: 2119218: root: ERROR:   File "/lib64/python3.8/site-packages/vmware/esximage/Transaction.py", line 965, in InstallVibsFromSources
2021-11-03T11:19:40Z esxupdate: 2119218: root: ERROR:     inst, removed, exitstate = self._installVibs(curprofile,
2021-11-03T11:19:40Z esxupdate: 2119218: root: ERROR:   File "/lib64/python3.8/site-packages/vmware/esximage/Transaction.py", line 1207, in _installVibs
2021-11-03T11:19:40Z esxupdate: 2119218: root: ERROR:     hasConfigDowngrade = checkFdmConfigDowngrade(curProfile, newProfile)
2021-11-03T11:19:40Z esxupdate: 2119218: root: ERROR:   File "/lib64/python3.8/site-packages/vmware/esximage/Transaction.py", line 1122, in checkFdmConfigDowngrade
2021-11-03T11:19:40Z esxupdate: 2119218: root: ERROR:     compDowngrades = curProfile.GetCompsDowngradeInfo(newProfile)
2021-11-03T11:19:40Z esxupdate: 2119218: root: ERROR:   File "/lib64/python3.8/site-packages/vmware/esximage/ImageProfile.py", line 2416, in GetCompsDowngradeInfo
2021-11-03T11:19:40Z esxupdate: 2119218: root: ERROR:     curComp = self.components.GetComponent(name)
2021-11-03T11:19:40Z esxupdate: 2119218: root: ERROR:   File "/lib64/python3.8/site-packages/vmware/esximage/Bulletin.py", line 1276, in GetComponent
2021-11-03T11:19:40Z esxupdate: 2119218: root: ERROR:     raise ValueError('Expected 1 component, found %u'
2021-11-03T11:19:40Z esxupdate: 2119218: root: ERROR: ValueError: Expected 1 component, found 2

```

I'm not sure if this is something that has been affected by the update to 7.03 as it was working ok on 7,02.

**Comment by paintballrefjosh** [comment]
Same problem here running 7.0.3 and cannot install successfully.  Error received:

> [ValueError]
> Expected 1 component, found 2
> Please refer to the log file for more details.

**Comment by Cardy165** [comment]
Just a quick update for anyone with this issue:

I believe this is related to the problems with update 7.03 (VMWare pulled this release due to problems) as documented : [https://kb.vmware.com/s/article/2143832](https://kb.vmware.com/s/article/2143832)

This does not solve the problem but I believe this is a VMWare problem so basically wait for the next update.
